treinamento_simples:
  regressao_linear:
    fit_intercept: true
    param_range_start: -3
    param_range_end: 2
    param_range_num: 10
    cv_folds: 5
    scoring: "neg_root_mean_squared_error"
    n_jobs: 4
    random_state: 42

  arvore_decisao:

carregador_dados:
  colunas:
    - "Metragem"
    - "Quartos"
    - "Banheiros"
    - "Vagas"
    - "Bairro"
    - "Valor_da_Venda"

mlflow:
  tracking_uri: "http://localhost:5000"
  nome_experimento: "Experimento_Previsão_Apartamentos_RP"
  nome_modelo_registry: "Modelo_Preco_Imoveis_RP"
